# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: metalearners
  version: ${{ env.get('GIT_DESCRIBE_TAG') | trim('v') }}${{ ('.post' + env.get('GIT_DESCRIBE_NUMBER') + '+' + env.get('GIT_DESCRIBE_HASH')) if env.get_default('GIT_DESCRIBE_NUMBER', '0') != '0' }}

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools-scm
  run:
    - python >=3.10
    - scikit-learn >=1.3
    - pandas
    - numpy
    - typing-extensions
    - git_root
    - shap
    - joblib >= 1.2.0
tests:
  - python:
      imports:
        - metalearners
        - metalearners.utils
        - metalearners.cross_fit_estimator
        - metalearners.data_generation
        - metalearners.outcome_functions
        - metalearners.tlearner
        - metalearners.slearner
        - metalearners.xlearner
        - metalearners.rlearner
        - metalearners.drlearner
        - metalearners.explainer
        - metalearners.grid_search
      pip_check: true

about:
  homepage: https://github.com/quantco/metalearners
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "MetaLearners for CATE estimation"
