name: Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

defaults:
  run:
    shell: bash -el {0}

jobs:
  run_benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: default lint benchmark
      - name: Install repository and run benchmarks
        run: |
          pixi run -e benchmark postinstall
          pixi run benchmark
      - name: Update readme.md
        run: |
          line_number=`grep "| T-learner" benchmarks/readme.md -n | cut -f1 -d:`
          head -n $(($line_number -1)) benchmarks/readme.md > benchmarks/new_readme.md
          cat benchmarks/comparison.md >> benchmarks/new_readme.md
          mv benchmarks/new_readme.md benchmarks/readme.md
      - name: Run pre-commit hooks
        run: pixi run pre-commit-run --color=always --show-diff-on-failure || true
      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Auto-update benchmarks/readme.md
          title: Auto-update benchmarks/readme.md
          body: |
            Update benchmarks/readme.md.
            Remember to update the corresponding values in `tests/test_learner.py`.
          branch: update-benchmarks
          delete-branch: true
          add-paths: benchmarks/readme.md
          draft: true
